defaults: &defaults
  serviceName: image-handler-test
  offlinePort: 80
  region: "us-east-1"
  environment: &defaults.environment
    DEFAULT_QUALITY: 75
    DEFAULT_COMPRESS_QUALITY: 45
    SLS_IGNORE: favicon.ico
    SLS_VALID_PATH_REGEX: ".*"
    MAX_IMAGE_WIDTH: 2000
    MAX_IMAGE_HEIGHT: 1000
    PNGQUANT_SPEED: 10

stages:
  dev:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: "my-bucket/prefix/path"
      SECURITY_KEY: ""
  prod:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: "random-string-here"
      SECURITY_KEY: ""
